version: "3"
services:
    web:
      container_name: 'web'
      build:
          context: web
      ports:
          - '8080:8080'
      links:
          - db
      depends_on:
          - db
    db:
      container_name: 'db'
      build:
          context: db
      ports:
          - '5432:5432'
      expose:
          - '5432'
